// Copyright (c) 2020 Google LLC All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package com.google.idea.gn.psi.builtin

import com.google.idea.gn.psi.FunctionVariable
import com.google.idea.gn.psi.GnCompositeType

enum class BuiltinVariable(override val identifierName: String, override val type: GnCompositeType) : FunctionVariable {
  DEPS("deps", GnCompositeType.LIST_OF_STRING),
  PUBLIC_DEPS("public_deps", GnCompositeType.LIST_OF_STRING),
  DATA_DEPS("data_deps", GnCompositeType.LIST_OF_STRING),
  INVOKER("invoker", GnCompositeType.SCOPE),
  SOURCES("sources", GnCompositeType.LIST_OF_STRING),
  ALL_DEPENDENT_CONFIGS("all_dependent_configs", GnCompositeType.LIST_OF_STRING),
  PUBLIC_CONFIGS("public_configs", GnCompositeType.LIST_OF_STRING),
  CFLAGS("cflags", GnCompositeType.LIST_OF_STRING),
  CFLAGS_C("cflags_c", GnCompositeType.LIST_OF_STRING),
  CFLAGS_CC("cflags_cc", GnCompositeType.LIST_OF_STRING),
  CFLAGS_OBJC("cflags_objc", GnCompositeType.LIST_OF_STRING),
  CFLAGS_OBJCC("cflags_objcc", GnCompositeType.LIST_OF_STRING),
  ASMFLAGS("asmflags", GnCompositeType.LIST_OF_STRING),
  DEFINES("defines", GnCompositeType.LIST_OF_STRING),
  INCLUDE_DIRS("include_dirs", GnCompositeType.LIST_OF_STRING),
  INPUTS("inputs", GnCompositeType.LIST_OF_STRING),
  LDFLAGS("ldflags", GnCompositeType.LIST_OF_STRING),
  LIB_DIRS("lib_dirs", GnCompositeType.LIST_OF_STRING),
  LIBS("libs", GnCompositeType.LIST_OF_STRING),
  PRECOMPILED_HEADER("precompiled_header", GnCompositeType.STRING),
  PRECOMPILED_SOURCE("precompiled_source", GnCompositeType.STRING),
  RUSTFLAGS("rustflags", GnCompositeType.LIST_OF_STRING),
  RUSTENV("rustenv", GnCompositeType.LIST_OF_STRING),
  CHECK_INCLUDES("check_includes", GnCompositeType.BOOL),
  CONFIGS("configs", GnCompositeType.LIST_OF_STRING),
  DATA("data", GnCompositeType.LIST_OF_STRING),
  FRIEND("friend", GnCompositeType.LIST_OF_STRING),
  METADATA("metadata", GnCompositeType.SCOPE),
  OUTPUT_NAME("output_name", GnCompositeType.STRING),
  OUTPUT_EXTENSION("output_extension", GnCompositeType.STRING),
  PUBLIC("public", GnCompositeType.LIST_OF_STRING),
  TESTONLY("testonly", GnCompositeType.BOOL),
  VISIBILITY("visibility", GnCompositeType.LIST_OF_STRING),
  ALIASED_DEPS("aliased_deps", GnCompositeType.SCOPE),
  CRATE_ROOT("crate_root", GnCompositeType.STRING),
  CRATE_NAME("crate_name", GnCompositeType.STRING),
  ARGS("args", GnCompositeType.LIST_OF_STRING),
  DEPFILE("depfile", GnCompositeType.STRING),
  RESPONSE_FILE_CONTENTS("response_file_contents", GnCompositeType.STRING),
  SCRIPT("script", GnCompositeType.STRING),
  OUTPUTS("outputs", GnCompositeType.LIST_OF_STRING),
  POOL("pool", GnCompositeType.STRING),
  BUNDLE_ROOT_DIR("bundle_root_dir", GnCompositeType.STRING),
  BUNDLE_CONTENTS_DIR("bundle_contents_dir", GnCompositeType.STRING),
  BUNDLE_RESOURCES_DIR("bundle_resources_dir", GnCompositeType.STRING),
  BUNDLE_EXECUTABLE_DIR("bundle_executable_dir", GnCompositeType.STRING),
  BUNDLE_DEPS_FILTER("bundle_deps_filter", GnCompositeType.LIST_OF_STRING),
  PRODUCT_TYPE("product_type", GnCompositeType.STRING),
  CODE_SIGNING_ARGS("code_signing_args", GnCompositeType.LIST_OF_STRING),
  CODE_SIGNING_SCRIPT("code_signing_script", GnCompositeType.STRING),
  CODE_SIGNING_SOURCES("code_signing_sources", GnCompositeType.LIST_OF_STRING),
  CODE_SIGNING_OUTPUTS("code_signing_outputs", GnCompositeType.LIST_OF_STRING),
  XCODE_EXTRA_ATTRIBUTES("xcode_extra_attributes", GnCompositeType.SCOPE),
  XCODE_TEST_APPLICATION_NAME("xcode_test_application_name", GnCompositeType.STRING),
  PARTIAL_INFO_PLIST("partial_info_plist", GnCompositeType.STRING),
  CONTENTS("contents", GnCompositeType.SCOPE),
  DATA_KEYS("data_keys", GnCompositeType.LIST_OF_STRING),
  REBASE("rebase", GnCompositeType.BOOL),
  WALK_KEYS("walk_keys", GnCompositeType.LIST_OF_STRING),
  OUTPUT_CONVERSION("output_conversion", GnCompositeType.STRING),
  CRATE_TYPE("crate_type", GnCompositeType.STRING),
  COMPLETE_STATIC_LIB("complete_static_lib", GnCompositeType.BOOL),

  ;
}
