name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Validate tag
        shell: bash
        run: |
          describe_tags=$(git describe --tags)
          if [[ ! "$describe_tags" =~ ^[0-9]+\.[0-9]+\.[0-9]$ ]]; then
              echo "Tag $describe_tags is not a valid tag name"
              exit 1
          fi
          echo "Building tag $describe_tags"

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          gradle-home-cache-cleanup: true

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Prepare Plugin Artifact
        id: artifact
        shell: bash
        run: |
          cd ./build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content

          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./build/distributions/content/*/*
